### PR TITLE
Modernize.

### PR DESCRIPTION
**Pull request by davidlehn**
(Note this was based on and targets update-deps branch, I think it could be retargeted at master)

### CODE REVIEW

**Review by JSAssassin — APPROVED** [review]

**Review by dmitrizagidulin — APPROVED** [review]
👍

**Review by dlongley — APPROVED** [review]
Yay! Thank you, @davidlehn!

**Comment by JSAssassin** [comment]
@davidlehn I made a small commit here just to fix spelling error and use master branch for vue-web-request-mediator. I noticed those errors when testing veres issuer/wallet.

**Comment by davidlehn** [comment]
@JSAssassin I was in the middle of releasing vue-web-request-mediator 3.0.0 and updating the dep.  You hit it at the exact wrong minute. :-) It should work with the update.

**Pull request merged**
